/**
 * Do not edit directly
 * Generated on Thu, 10 Nov 2022 00:25:36 GMT
 * Next will implement directly from design-token generated with style-dictionary
 */

export const ColorM3SysLightPrimary = '#6750a4'; // done
export const ColorM3SysLightOnPrimary = '#ffffff'; // done
export const ColorM3SysLightPrimaryContainer = '#eaddff'; // done
export const ColorM3SysLightOnPrimaryContainer = '#21005d'; // done
export const ColorM3SysLightSecondary = '#625b71'; // done
export const ColorM3SysLightOnSecondary = '#ffffff'; // done
export const ColorM3SysLightSecondaryContainer = '#e8def8'; // done
export const ColorM3SysLightOnSecondaryContainer = '#1d192b'; // done
export const ColorM3SysLightTertiary = '#7d5260'; // done
export const ColorM3SysLightOnTertiary = '#ffffff'; // done
export const ColorM3SysLightTertiaryContainer = '#ffd8e4'; // done
export const ColorM3SysLightOnTertiaryContainer = '#31111d'; // done
export const ColorM3SysLightError = '#b3261e'; // done
export const ColorM3SysLightErrorContainer = '#f9dedc'; // done
export const ColorM3SysLightOnError = '#ffffff'; // done
export const ColorM3SysLightOnErrorContainer = '#410e0b'; // done
export const ColorM3SysLightBackground = '#fffbfe'; // done
export const ColorM3SysLightOnBackground = '#1c1b1f'; // done
export const ColorM3SysLightSurface = '#fffbfe'; // done
export const ColorM3SysLightOnSurface = '#1c1b1f'; // done
export const ColorM3SysLightSurfaceVariant = '#e7e0ec'; // done
export const ColorM3SysLightOnSurfaceVariant = '#49454f'; // done
export const ColorM3SysLightOutline = '#79747e'; // done
export const ColorM3SysLightInverseOnSurface = '#f4eff4'; // done
export const ColorM3SysLightInverseSurface = '#313033'; // done
export const ColorM3SysDarkPrimary = '#d0bcff'; // done
export const ColorM3SysDarkOnPrimary = '#381e72'; // done
export const ColorM3SysDarkPrimaryContainer = '#4f378b'; // done
export const ColorM3SysDarkOnPrimaryContainer = '#eaddff'; // done
export const ColorM3SysDarkSecondary = '#ccc2dc'; // done
export const ColorM3SysDarkOnSecondary = '#332d41'; // done
export const ColorM3SysDarkSecondaryContainer = '#4a4458'; // done
export const ColorM3SysDarkOnSecondaryContainer = '#e8def8'; // done
export const ColorM3SysDarkTertiary = '#efb8c8'; // done
export const ColorM3SysDarkOnTertiary = '#492532'; // done
export const ColorM3SysDarkTertiaryContainer = '#633b48'; // done
export const ColorM3SysDarkOnTertiaryContainer = '#ffd8e4'; // done
export const ColorM3SysDarkError = '#f2b8b5'; // done
export const ColorM3SysDarkErrorContainer = '#8c1d18'; // done
export const ColorM3SysDarkOnError = '#601410'; // done
export const ColorM3SysDarkOnErrorContainer = '#f9dedc'; // done
export const ColorM3SysDarkBackground = '#1c1b1f'; // done
export const ColorM3SysDarkOnBackground = '#e6e1e5'; // done
export const ColorM3SysDarkSurface = '#1c1b1f'; // done
export const ColorM3SysDarkOnSurface = '#e6e1e5'; // done
export const ColorM3SysDarkSurfaceVariant = '#49454f'; // done
export const ColorM3SysDarkOnSurfaceVariant = '#cac4d0'; // done
export const ColorM3SysDarkOutline = '#938f99'; // done
export const ColorM3SysDarkInverseOnSurface = '#1c1b1f'; // done
export const ColorM3SysDarkInverseSurface = '#e6e1e5'; // done
export const ColorM3RefPrimaryPrimary100 = '#ffffff';
export const ColorM3RefPrimaryPrimary99 = '#fffbfe';
export const ColorM3RefPrimaryPrimary95 = '#f6edff';
export const ColorM3RefPrimaryPrimary90 = '#eaddff';
export const ColorM3RefPrimaryPrimary80 = '#d0bcff';
export const ColorM3RefPrimaryPrimary70 = '#b69df8';
export const ColorM3RefPrimaryPrimary60 = '#9a82db';
export const ColorM3RefPrimaryPrimary50 = '#7f67be';
export const ColorM3RefPrimaryPrimary40 = '#6750a4';
export const ColorM3RefPrimaryPrimary30 = '#4f378b';
export const ColorM3RefPrimaryPrimary20 = '#381e72';
export const ColorM3RefPrimaryPrimary10 = '#21005d';
export const ColorM3RefPrimaryPrimary0 = '#000000';
export const ColorM3RefSecondarySecondary100 = '#ffffff';
export const ColorM3RefSecondarySecondary99 = '#fffbfe';
export const ColorM3RefSecondarySecondary95 = '#f6edff';
export const ColorM3RefSecondarySecondary90 = '#e8def8';
export const ColorM3RefSecondarySecondary80 = '#ccc2dc';
export const ColorM3RefSecondarySecondary70 = '#b0a7c0';
export const ColorM3RefSecondarySecondary60 = '#958da5';
export const ColorM3RefSecondarySecondary50 = '#7a7289';
export const ColorM3RefSecondarySecondary40 = '#625b71';
export const ColorM3RefSecondarySecondary30 = '#4a4458';
export const ColorM3RefSecondarySecondary20 = '#332d41';
export const ColorM3RefSecondarySecondary10 = '#1d192b';
export const ColorM3RefSecondarySecondary0 = '#000000';
export const ColorM3RefTertiaryTertiary100 = '#ffffff';
export const ColorM3RefTertiaryTertiary99 = '#fffbfa';
export const ColorM3RefTertiaryTertiary95 = '#ffecf1';
export const ColorM3RefTertiaryTertiary90 = '#ffd8e4';
export const ColorM3RefTertiaryTertiary80 = '#efb8c8';
export const ColorM3RefTertiaryTertiary70 = '#d29dac';
export const ColorM3RefTertiaryTertiary60 = '#b58392';
export const ColorM3RefTertiaryTertiary50 = '#986977';
export const ColorM3RefTertiaryTertiary40 = '#7d5260';
export const ColorM3RefTertiaryTertiary30 = '#633b48';
export const ColorM3RefTertiaryTertiary20 = '#492532';
export const ColorM3RefTertiaryTertiary10 = '#31111d';
export const ColorM3RefTertiaryTertiary0 = '#000000';
export const ColorM3RefNeutralNeutral100 = '#ffffff';
export const ColorM3RefNeutralNeutral99 = '#fffbfe';
export const ColorM3RefNeutralNeutral95 = '#f4eff4';
export const ColorM3RefNeutralNeutral90 = '#e6e1e5';
export const ColorM3RefNeutralNeutral80 = '#c9c5ca';
export const ColorM3RefNeutralNeutral70 = '#aeaaae';
export const ColorM3RefNeutralNeutral60 = '#939094';
export const ColorM3RefNeutralNeutral50 = '#787579';
export const ColorM3RefNeutralNeutral40 = '#605d62';
export const ColorM3RefNeutralNeutral30 = '#484649';
export const ColorM3RefNeutralNeutral20 = '#313033';
export const ColorM3RefNeutralNeutral10 = '#1c1b1f';
export const ColorM3RefNeutralNeutral0 = '#000000';
export const ColorM3RefNeutralVariantNeutralVariant100 = '#ffffff';
export const ColorM3RefNeutralVariantNeutralVariant99 = '#fffbfe';
export const ColorM3RefNeutralVariantNeutralVariant95 = '#f5eefa';
export const ColorM3RefNeutralVariantNeutralVariant90 = '#e7e0ec';
export const ColorM3RefNeutralVariantNeutralVariant80 = '#cac4d0';
export const ColorM3RefNeutralVariantNeutralVariant70 = '#aea9b4';
export const ColorM3RefNeutralVariantNeutralVariant60 = '#938f99';
export const ColorM3RefNeutralVariantNeutralVariant50 = '#79747e';
export const ColorM3RefNeutralVariantNeutralVariant40 = '#605d66';
export const ColorM3RefNeutralVariantNeutralVariant30 = '#49454f';
export const ColorM3RefNeutralVariantNeutralVariant20 = '#322f37';
export const ColorM3RefNeutralVariantNeutralVariant10 = '#1d1a22';
export const ColorM3RefNeutralVariantNeutralVariant0 = '#000000';
export const ColorM3RefErrorError100 = '#ffffff';
export const ColorM3RefErrorError99 = '#fffbf9';
export const ColorM3RefErrorError95 = '#fceeee';
export const ColorM3RefErrorError90 = '#f9dedc';
export const ColorM3RefErrorError80 = '#f2b8b5';
export const ColorM3RefErrorError70 = '#ec928e';
export const ColorM3RefErrorError60 = '#e46962';
export const ColorM3RefErrorError50 = '#dc362e';
export const ColorM3RefErrorError40 = '#b3261e';
export const ColorM3RefErrorError30 = '#8c1d18';
export const ColorM3RefErrorError20 = '#601410';
export const ColorM3RefErrorError10 = '#410e0b';
export const ColorM3RefErrorError0 = '#000000';
export const ColorM3SourceSeed = '#6750a4';
export const ColorM3SourcePrimary = '#6750a4';
export const ColorM3SourceSecondary = '#625b71';
export const ColorM3SourceTertiary = '#7d5260';
export const ColorM3SourceNeutral = '#605d62';
export const ColorM3SourceNeutralVariant = '#605d66';
export const ColorM3SourceError = '#b3261e';
export const ColorM3ReadOnlyLightSurface10 = '#fffbfe';
export const ColorM3ReadOnlyLightSurface11 = '#6750a4';
export const ColorM3ReadOnlyLightSurface20 = '#fffbfe';
export const ColorM3ReadOnlyLightSurface21 = '#6750a4';
export const ColorM3ReadOnlyLightSurface30 = '#fffbfe';
export const ColorM3ReadOnlyLightSurface31 = '#6750a4';
export const ColorM3ReadOnlyLightSurface40 = '#fffbfe';
export const ColorM3ReadOnlyLightSurface41 = '#6750a4';
export const ColorM3ReadOnlyLightSurface50 = '#fffbfe';
export const ColorM3ReadOnlyLightSurface51 = '#6750a4';
export const ColorM3ReadOnlyLightBlack = '#000000';
export const ColorM3ReadOnlyLightWhite = '#ffffff';
export const ColorM3ReadOnlyLightPrimaryOpacity008 = '#6750a4';
export const ColorM3ReadOnlyLightPrimaryOpacity012 = '#6750a4';
export const ColorM3ReadOnlyLightPrimaryOpacity016 = '#6750a4';
export const ColorM3ReadOnlyLightOnPrimaryOpacity008 = '#ffffff';
export const ColorM3ReadOnlyLightOnPrimaryOpacity012 = '#ffffff';
export const ColorM3ReadOnlyLightOnPrimaryOpacity016 = '#ffffff';
export const ColorM3ReadOnlyLightOnPrimaryContainerOpacity008 = '#21005d';
export const ColorM3ReadOnlyLightOnPrimaryContainerOpacity012 = '#21005d';
export const ColorM3ReadOnlyLightOnPrimaryContainerOpacity016 = '#21005d';
export const ColorM3ReadOnlyLightSecondaryOpacity008 = '#625b71';
export const ColorM3ReadOnlyLightSecondaryOpacity012 = '#625b71';
export const ColorM3ReadOnlyLightSecondaryOpacity016 = '#625b71';
export const ColorM3ReadOnlyLightOnSecondaryOpacity008 = '#ffffff';
export const ColorM3ReadOnlyLightOnSecondaryOpacity012 = '#ffffff';
export const ColorM3ReadOnlyLightOnSecondaryOpacity016 = '#ffffff';
export const ColorM3ReadOnlyLightOnSecondaryContainerOpacity008 = '#1d192b';
export const ColorM3ReadOnlyLightOnSecondaryContainerOpacity012 = '#1d192b';
export const ColorM3ReadOnlyLightOnSecondaryContainerOpacity016 = '#1d192b';
export const ColorM3ReadOnlyLightTertiaryOpacity008 = '#7d5260';
export const ColorM3ReadOnlyLightTertiaryOpacity012 = '#7d5260';
export const ColorM3ReadOnlyLightTertiaryOpacity016 = '#7d5260';
export const ColorM3ReadOnlyLightOnTertiaryOpacity008 = '#ffffff';
export const ColorM3ReadOnlyLightOnTertiaryOpacity012 = '#ffffff';
export const ColorM3ReadOnlyLightOnTertiaryOpacity016 = '#ffffff';
export const ColorM3ReadOnlyLightOnTertiaryContainerOpacity008 = '#31111d';
export const ColorM3ReadOnlyLightOnTertiaryContainerOpacity012 = '#31111d';
export const ColorM3ReadOnlyLightOnTertiaryContainerOpacity016 = '#31111d';
export const ColorM3ReadOnlyLightPrimaryContainerOpacity008 = '#eaddff';
export const ColorM3ReadOnlyLightPrimaryContainerOpacity012 = '#eaddff';
export const ColorM3ReadOnlyLightPrimaryContainerOpacity016 = '#eaddff';
export const ColorM3ReadOnlyLightSecondaryContainerOpacity008 = '#e8def8';
export const ColorM3ReadOnlyLightSecondaryContainerOpacity012 = '#e8def8';
export const ColorM3ReadOnlyLightSecondaryContainerOpacity016 = '#e8def8';
export const ColorM3ReadOnlyLightTertiaryContainerOpacity008 = '#ffd8e4';
export const ColorM3ReadOnlyLightTertiaryContainerOpacity012 = '#ffd8e4';
export const ColorM3ReadOnlyLightTertiaryContainerOpacity016 = '#ffd8e4';
export const ColorM3ReadOnlyLightErrorOpacity008 = '#b3261e';
export const ColorM3ReadOnlyLightErrorOpacity012 = '#b3261e';
export const ColorM3ReadOnlyLightErrorOpacity016 = '#b3261e';
export const ColorM3ReadOnlyLightErrorContainerOpacity008 = '#f9dedc';
export const ColorM3ReadOnlyLightErrorContainerOpacity012 = '#f9dedc';
export const ColorM3ReadOnlyLightErrorContainerOpacity016 = '#f9dedc';
export const ColorM3ReadOnlyLightOnErrorOpacity008 = '#ffffff';
export const ColorM3ReadOnlyLightOnErrorOpacity012 = '#ffffff';
export const ColorM3ReadOnlyLightOnErrorOpacity016 = '#ffffff';
export const ColorM3ReadOnlyLightOnErrorContainerOpacity008 = '#410e0b';
export const ColorM3ReadOnlyLightOnErrorContainerOpacity012 = '#410e0b';
export const ColorM3ReadOnlyLightOnErrorContainerOpacity016 = '#410e0b';
export const ColorM3ReadOnlyLightBackgroundOpacity008 = '#fffbfe';
export const ColorM3ReadOnlyLightBackgroundOpacity012 = '#fffbfe';
export const ColorM3ReadOnlyLightBackgroundOpacity016 = '#fffbfe';
export const ColorM3ReadOnlyLightOnBackgroundOpacity008 = '#1c1b1f';
export const ColorM3ReadOnlyLightOnBackgroundOpacity012 = '#1c1b1f';
export const ColorM3ReadOnlyLightOnBackgroundOpacity016 = '#1c1b1f';
export const ColorM3ReadOnlyLightSurfaceOpacity008 = '#fffbfe';
export const ColorM3ReadOnlyLightSurfaceOpacity012 = '#fffbfe';
export const ColorM3ReadOnlyLightSurfaceOpacity016 = '#fffbfe';
export const ColorM3ReadOnlyLightOnSurfaceOpacity008 = '#1c1b1f';
export const ColorM3ReadOnlyLightOnSurfaceOpacity012 = '#1c1b1f';
export const ColorM3ReadOnlyLightOnSurfaceOpacity016 = '#1c1b1f';
export const ColorM3ReadOnlyLightSurfaceVariantOpacity008 = '#e7e0ec';
export const ColorM3ReadOnlyLightSurfaceVariantOpacity012 = '#e7e0ec';
export const ColorM3ReadOnlyLightSurfaceVariantOpacity016 = '#e7e0ec';
export const ColorM3ReadOnlyLightOnSurfaceVariantOpacity008 = '#49454f';
export const ColorM3ReadOnlyLightOnSurfaceVariantOpacity012 = '#49454f';
export const ColorM3ReadOnlyLightOnSurfaceVariantOpacity016 = '#49454f';
export const ColorM3ReadOnlyLightOutlineOpacity008 = '#79747e';
export const ColorM3ReadOnlyLightOutlineOpacity012 = '#79747e';
export const ColorM3ReadOnlyLightOutlineOpacity016 = '#79747e';
export const ColorM3ReadOnlyLightInverseOnSurfaceOpacity008 = '#f4eff4';
export const ColorM3ReadOnlyLightInverseOnSurfaceOpacity012 = '#f4eff4';
export const ColorM3ReadOnlyLightInverseOnSurfaceOpacity016 = '#f4eff4';
export const ColorM3ReadOnlyLightInverseSurfaceOpacity008 = '#313033';
export const ColorM3ReadOnlyLightInverseSurfaceOpacity012 = '#313033';
export const ColorM3ReadOnlyLightInverseSurfaceOpacity016 = '#313033';
export const ColorM3ReadOnlyDarkSurface10 = '#1c1b1f';
export const ColorM3ReadOnlyDarkSurface11 = '#d0bcff';
export const ColorM3ReadOnlyDarkSurface20 = '#1c1b1f';
export const ColorM3ReadOnlyDarkSurface21 = '#d0bcff';
export const ColorM3ReadOnlyDarkSurface30 = '#1c1b1f';
export const ColorM3ReadOnlyDarkSurface31 = '#d0bcff';
export const ColorM3ReadOnlyDarkSurface40 = '#1c1b1f';
export const ColorM3ReadOnlyDarkSurface41 = '#d0bcff';
export const ColorM3ReadOnlyDarkSurface50 = '#1c1b1f';
export const ColorM3ReadOnlyDarkSurface51 = '#d0bcff';
export const ColorM3ReadOnlyDarkWhite = '#ffffff';
export const ColorM3ReadOnlyDarkBlack = '#000000';
export const ColorM3ReadOnlyDarkPrimaryOpacity008 = '#d0bcff';
export const ColorM3ReadOnlyDarkPrimaryOpacity012 = '#d0bcff';
export const ColorM3ReadOnlyDarkPrimaryOpacity016 = '#d0bcff';
export const ColorM3ReadOnlyDarkOnPrimaryOpacity008 = '#381e72';
export const ColorM3ReadOnlyDarkOnPrimaryOpacity012 = '#381e72';
export const ColorM3ReadOnlyDarkOnPrimaryOpacity016 = '#381e72';
export const ColorM3ReadOnlyDarkOnPrimaryContainerOpacity008 = '#eaddff';
export const ColorM3ReadOnlyDarkOnPrimaryContainerOpacity012 = '#eaddff';
export const ColorM3ReadOnlyDarkOnPrimaryContainerOpacity016 = '#eaddff';
export const ColorM3ReadOnlyDarkSecondaryOpacity008 = '#ccc2dc';
export const ColorM3ReadOnlyDarkSecondaryOpacity012 = '#ccc2dc';
export const ColorM3ReadOnlyDarkSecondaryOpacity016 = '#ccc2dc';
export const ColorM3ReadOnlyDarkOnSecondaryOpacity008 = '#332d41';
export const ColorM3ReadOnlyDarkOnSecondaryOpacity012 = '#332d41';
export const ColorM3ReadOnlyDarkOnSecondaryOpacity016 = '#332d41';
export const ColorM3ReadOnlyDarkOnSecondaryContainerOpacity008 = '#e8def8';
export const ColorM3ReadOnlyDarkOnSecondaryContainerOpacity012 = '#e8def8';
export const ColorM3ReadOnlyDarkOnSecondaryContainerOpacity016 = '#e8def8';
export const ColorM3ReadOnlyDarkTertiaryOpacity008 = '#efb8c8';
export const ColorM3ReadOnlyDarkTertiaryOpacity012 = '#efb8c8';
export const ColorM3ReadOnlyDarkTertiaryOpacity016 = '#efb8c8';
export const ColorM3ReadOnlyDarkOnTertiaryOpacity008 = '#492532';
export const ColorM3ReadOnlyDarkOnTertiaryOpacity012 = '#492532';
export const ColorM3ReadOnlyDarkOnTertiaryOpacity016 = '#492532';
export const ColorM3ReadOnlyDarkOnTertiaryContainerOpacity008 = '#ffd8e4';
export const ColorM3ReadOnlyDarkOnTertiaryContainerOpacity012 = '#ffd8e4';
export const ColorM3ReadOnlyDarkOnTertiaryContainerOpacity016 = '#ffd8e4';
export const ColorM3ReadOnlyDarkPrimaryContainerOpacity008 = '#4f378b';
export const ColorM3ReadOnlyDarkPrimaryContainerOpacity012 = '#4f378b';
export const ColorM3ReadOnlyDarkPrimaryContainerOpacity016 = '#4f378b';
export const ColorM3ReadOnlyDarkSecondaryContainerOpacity008 = '#4a4458';
export const ColorM3ReadOnlyDarkSecondaryContainerOpacity012 = '#4a4458';
export const ColorM3ReadOnlyDarkSecondaryContainerOpacity016 = '#4a4458';
export const ColorM3ReadOnlyDarkTertiaryContainerOpacity008 = '#633b48';
export const ColorM3ReadOnlyDarkTertiaryContainerOpacity012 = '#633b48';
export const ColorM3ReadOnlyDarkTertiaryContainerOpacity016 = '#633b48';
export const ColorM3ReadOnlyDarkErrorOpacity008 = '#f2b8b5';
export const ColorM3ReadOnlyDarkErrorOpacity012 = '#f2b8b5';
export const ColorM3ReadOnlyDarkErrorOpacity016 = '#f2b8b5';
export const ColorM3ReadOnlyDarkErrorContainerOpacity008 = '#8c1d18';
export const ColorM3ReadOnlyDarkErrorContainerOpacity012 = '#8c1d18';
export const ColorM3ReadOnlyDarkErrorContainerOpacity016 = '#8c1d18';
export const ColorM3ReadOnlyDarkOnErrorOpacity008 = '#601410';
export const ColorM3ReadOnlyDarkOnErrorOpacity012 = '#601410';
export const ColorM3ReadOnlyDarkOnErrorOpacity016 = '#601410';
export const ColorM3ReadOnlyDarkOnErrorContainerOpacity008 = '#f9dedc';
export const ColorM3ReadOnlyDarkOnErrorContainerOpacity012 = '#f9dedc';
export const ColorM3ReadOnlyDarkOnErrorContainerOpacity016 = '#f9dedc';
export const ColorM3ReadOnlyDarkBackgroundOpacity008 = '#1c1b1f';
export const ColorM3ReadOnlyDarkBackgroundOpacity012 = '#1c1b1f';
export const ColorM3ReadOnlyDarkBackgroundOpacity016 = '#1c1b1f';
export const ColorM3ReadOnlyDarkOnBackgroundOpacity008 = '#e6e1e5';
export const ColorM3ReadOnlyDarkOnBackgroundOpacity012 = '#e6e1e5';
export const ColorM3ReadOnlyDarkOnBackgroundOpacity016 = '#e6e1e5';
export const ColorM3ReadOnlyDarkSurfaceOpacity008 = '#1c1b1f';
export const ColorM3ReadOnlyDarkSurfaceOpacity012 = '#1c1b1f';
export const ColorM3ReadOnlyDarkSurfaceOpacity016 = '#1c1b1f';
export const ColorM3ReadOnlyDarkOnSurfaceOpacity008 = '#e6e1e5';
export const ColorM3ReadOnlyDarkOnSurfaceOpacity012 = '#e6e1e5';
export const ColorM3ReadOnlyDarkOnSurfaceOpacity016 = '#e6e1e5';
export const ColorM3ReadOnlyDarkSurfaceVariantOpacity008 = '#49454f';
export const ColorM3ReadOnlyDarkSurfaceVariantOpacity012 = '#49454f';
export const ColorM3ReadOnlyDarkSurfaceVariantOpacity016 = '#49454f';
export const ColorM3ReadOnlyDarkOnSurfaceVariantOpacity008 = '#cac4d0';
export const ColorM3ReadOnlyDarkOnSurfaceVariantOpacity012 = '#cac4d0';
export const ColorM3ReadOnlyDarkOnSurfaceVariantOpacity016 = '#cac4d0';
export const ColorM3ReadOnlyDarkOutlineOpacity008 = '#938f99';
export const ColorM3ReadOnlyDarkOutlineOpacity012 = '#938f99';
export const ColorM3ReadOnlyDarkOutlineOpacity016 = '#938f99';
export const ColorM3ReadOnlyDarkInverseOnSurfaceOpacity008 = '#1c1b1f';
export const ColorM3ReadOnlyDarkInverseOnSurfaceOpacity012 = '#1c1b1f';
export const ColorM3ReadOnlyDarkInverseOnSurfaceOpacity016 = '#1c1b1f';
export const ColorM3ReadOnlyDarkInverseSurfaceOpacity008 = '#e6e1e5';
export const ColorM3ReadOnlyDarkInverseSurfaceOpacity012 = '#e6e1e5';
export const ColorM3ReadOnlyDarkInverseSurfaceOpacity016 = '#e6e1e5';
