import {MD2Colors as Colors, MD3DarkTheme as DarkTheme, DefaultTheme} from 'react-native-paper';

import {
  ColorM3SysLightPrimary,
  ColorM3SysLightOnPrimary,
  ColorM3SysLightPrimaryContainer,
  ColorM3SysLightOnPrimaryContainer,
  ColorM3SysLightSecondary,
  ColorM3SysLightOnSecondary,
  ColorM3SysLightSecondaryContainer,
  ColorM3SysLightOnSecondaryContainer,
  ColorM3SysLightTertiary,
  ColorM3SysLightOnTertiary,
  ColorM3SysLightTertiaryContainer,
  ColorM3SysLightOnTertiaryContainer,
  ColorM3SysLightError,
  ColorM3SysLightErrorContainer,
  ColorM3SysLightOnError,
  ColorM3SysLightOnErrorContainer,
  ColorM3SysLightBackground,
  ColorM3SysLightOnBackground,
  ColorM3SysLightSurface,
  ColorM3SysLightOnSurface,
  ColorM3SysLightSurfaceVariant,
  ColorM3SysLightOnSurfaceVariant,
  ColorM3SysLightOutline,
  ColorM3SysLightInverseOnSurface,
  ColorM3SysLightInverseSurface,
  ColorM3SysDarkPrimary,
  ColorM3SysDarkOnPrimary,
  ColorM3SysDarkPrimaryContainer,
  ColorM3SysDarkOnPrimaryContainer,
  ColorM3SysDarkSecondary,
  ColorM3SysDarkOnSecondary,
  ColorM3SysDarkSecondaryContainer,
  ColorM3SysDarkOnSecondaryContainer,
  ColorM3SysDarkTertiary,
  ColorM3SysDarkOnTertiary,
  ColorM3SysDarkTertiaryContainer,
  ColorM3SysDarkOnTertiaryContainer,
  ColorM3SysDarkError,
  ColorM3SysDarkErrorContainer,
  ColorM3SysDarkOnError,
  ColorM3SysDarkOnErrorContainer,
  ColorM3SysDarkBackground,
  ColorM3SysDarkOnBackground,
  ColorM3SysDarkSurface,
  ColorM3SysDarkOnSurface,
  ColorM3SysDarkSurfaceVariant,
  ColorM3SysDarkOnSurfaceVariant,
  ColorM3SysDarkOutline,
  ColorM3SysDarkInverseOnSurface,
  ColorM3SysDarkInverseSurface,
  ColorM3RefPrimaryPrimary100,
  ColorM3RefPrimaryPrimary99,
  ColorM3RefPrimaryPrimary95,
  ColorM3RefPrimaryPrimary90,
  ColorM3RefPrimaryPrimary80,
  ColorM3RefPrimaryPrimary70,
  ColorM3RefPrimaryPrimary60,
  ColorM3RefPrimaryPrimary50,
  ColorM3RefPrimaryPrimary40,
  ColorM3RefPrimaryPrimary30,
  ColorM3RefPrimaryPrimary20,
  ColorM3RefPrimaryPrimary10,
  ColorM3RefPrimaryPrimary0,
  ColorM3RefSecondarySecondary100,
  ColorM3RefSecondarySecondary99,
  ColorM3RefSecondarySecondary95,
  ColorM3RefSecondarySecondary90,
  ColorM3RefSecondarySecondary80,
  ColorM3RefSecondarySecondary70,
  ColorM3RefSecondarySecondary60,
  ColorM3RefSecondarySecondary50,
  ColorM3RefSecondarySecondary40,
  ColorM3RefSecondarySecondary30,
  ColorM3RefSecondarySecondary20,
  ColorM3RefSecondarySecondary10,
  ColorM3RefSecondarySecondary0,
  ColorM3RefTertiaryTertiary100,
  ColorM3RefTertiaryTertiary99,
  ColorM3RefTertiaryTertiary95,
  ColorM3RefTertiaryTertiary90,
  ColorM3RefTertiaryTertiary80,
  ColorM3RefTertiaryTertiary70,
  ColorM3RefTertiaryTertiary60,
  ColorM3RefTertiaryTertiary50,
  ColorM3RefTertiaryTertiary40,
  ColorM3RefTertiaryTertiary30,
  ColorM3RefTertiaryTertiary20,
  ColorM3RefTertiaryTertiary10,
  ColorM3RefTertiaryTertiary0,
  ColorM3RefNeutralNeutral100,
  ColorM3RefNeutralNeutral99,
  ColorM3RefNeutralNeutral95,
  ColorM3RefNeutralNeutral90,
  ColorM3RefNeutralNeutral80,
  ColorM3RefNeutralNeutral70,
  ColorM3RefNeutralNeutral60,
  ColorM3RefNeutralNeutral50,
  ColorM3RefNeutralNeutral40,
  ColorM3RefNeutralNeutral30,
  ColorM3RefNeutralNeutral20,
  ColorM3RefNeutralNeutral10,
  ColorM3RefNeutralNeutral0,
  ColorM3RefNeutralVariantNeutralVariant100,
  ColorM3RefNeutralVariantNeutralVariant99,
  ColorM3RefNeutralVariantNeutralVariant95,
  ColorM3RefNeutralVariantNeutralVariant90,
  ColorM3RefNeutralVariantNeutralVariant80,
  ColorM3RefNeutralVariantNeutralVariant70,
  ColorM3RefNeutralVariantNeutralVariant60,
  ColorM3RefNeutralVariantNeutralVariant50,
  ColorM3RefNeutralVariantNeutralVariant40,
  ColorM3RefNeutralVariantNeutralVariant30,
  ColorM3RefNeutralVariantNeutralVariant20,
  ColorM3RefNeutralVariantNeutralVariant10,
  ColorM3RefNeutralVariantNeutralVariant0,
  ColorM3RefErrorError100,
  ColorM3RefErrorError99,
  ColorM3RefErrorError95,
  ColorM3RefErrorError90,
  ColorM3RefErrorError80,
  ColorM3RefErrorError70,
  ColorM3RefErrorError60,
  ColorM3RefErrorError50,
  ColorM3RefErrorError40,
  ColorM3RefErrorError30,
  ColorM3RefErrorError20,
  ColorM3RefErrorError10,
  ColorM3RefErrorError0,
  ColorM3SourceSeed,
  ColorM3SourcePrimary,
  ColorM3SourceSecondary,
  ColorM3SourceTertiary,
  ColorM3SourceNeutral,
  ColorM3SourceNeutralVariant,
  ColorM3SourceError,
  ColorM3ReadOnlyLightSurface10,
  ColorM3ReadOnlyLightSurface11,
  ColorM3ReadOnlyLightSurface20,
  ColorM3ReadOnlyLightSurface21,
  ColorM3ReadOnlyLightSurface30,
  ColorM3ReadOnlyLightSurface31,
  ColorM3ReadOnlyLightSurface40,
  ColorM3ReadOnlyLightSurface41,
  ColorM3ReadOnlyLightSurface50,
  ColorM3ReadOnlyLightSurface51,
  ColorM3ReadOnlyLightBlack,
  ColorM3ReadOnlyLightWhite,
  ColorM3ReadOnlyLightPrimaryOpacity008,
  ColorM3ReadOnlyLightPrimaryOpacity012,
  ColorM3ReadOnlyLightPrimaryOpacity016,
  ColorM3ReadOnlyLightOnPrimaryOpacity008,
  ColorM3ReadOnlyLightOnPrimaryOpacity012,
  ColorM3ReadOnlyLightOnPrimaryOpacity016,
  ColorM3ReadOnlyLightOnPrimaryContainerOpacity008,
  ColorM3ReadOnlyLightOnPrimaryContainerOpacity012,
  ColorM3ReadOnlyLightOnPrimaryContainerOpacity016,
  ColorM3ReadOnlyLightSecondaryOpacity008,
  ColorM3ReadOnlyLightSecondaryOpacity012,
  ColorM3ReadOnlyLightSecondaryOpacity016,
  ColorM3ReadOnlyLightOnSecondaryOpacity008,
  ColorM3ReadOnlyLightOnSecondaryOpacity012,
  ColorM3ReadOnlyLightOnSecondaryOpacity016,
  ColorM3ReadOnlyLightOnSecondaryContainerOpacity008,
  ColorM3ReadOnlyLightOnSecondaryContainerOpacity012,
  ColorM3ReadOnlyLightOnSecondaryContainerOpacity016,
  ColorM3ReadOnlyLightTertiaryOpacity008,
  ColorM3ReadOnlyLightTertiaryOpacity012,
  ColorM3ReadOnlyLightTertiaryOpacity016,
  ColorM3ReadOnlyLightOnTertiaryOpacity008,
  ColorM3ReadOnlyLightOnTertiaryOpacity012,
  ColorM3ReadOnlyLightOnTertiaryOpacity016,
  ColorM3ReadOnlyLightOnTertiaryContainerOpacity008,
  ColorM3ReadOnlyLightOnTertiaryContainerOpacity012,
  ColorM3ReadOnlyLightOnTertiaryContainerOpacity016,
  ColorM3ReadOnlyLightPrimaryContainerOpacity008,
  ColorM3ReadOnlyLightPrimaryContainerOpacity012,
  ColorM3ReadOnlyLightPrimaryContainerOpacity016,
  ColorM3ReadOnlyLightSecondaryContainerOpacity008,
  ColorM3ReadOnlyLightSecondaryContainerOpacity012,
  ColorM3ReadOnlyLightSecondaryContainerOpacity016,
  ColorM3ReadOnlyLightTertiaryContainerOpacity008,
  ColorM3ReadOnlyLightTertiaryContainerOpacity012,
  ColorM3ReadOnlyLightTertiaryContainerOpacity016,
  ColorM3ReadOnlyLightErrorOpacity008,
  ColorM3ReadOnlyLightErrorOpacity012,
  ColorM3ReadOnlyLightErrorOpacity016,
  ColorM3ReadOnlyLightErrorContainerOpacity008,
  ColorM3ReadOnlyLightErrorContainerOpacity012,
  ColorM3ReadOnlyLightErrorContainerOpacity016,
  ColorM3ReadOnlyLightOnErrorOpacity008,
  ColorM3ReadOnlyLightOnErrorOpacity012,
  ColorM3ReadOnlyLightOnErrorOpacity016,
  ColorM3ReadOnlyLightOnErrorContainerOpacity008,
  ColorM3ReadOnlyLightOnErrorContainerOpacity012,
  ColorM3ReadOnlyLightOnErrorContainerOpacity016,
  ColorM3ReadOnlyLightBackgroundOpacity008,
  ColorM3ReadOnlyLightBackgroundOpacity012,
  ColorM3ReadOnlyLightBackgroundOpacity016,
  ColorM3ReadOnlyLightOnBackgroundOpacity008,
  ColorM3ReadOnlyLightOnBackgroundOpacity012,
  ColorM3ReadOnlyLightOnBackgroundOpacity016,
  ColorM3ReadOnlyLightSurfaceOpacity008,
  ColorM3ReadOnlyLightSurfaceOpacity012,
  ColorM3ReadOnlyLightSurfaceOpacity016,
  ColorM3ReadOnlyLightOnSurfaceOpacity008,
  ColorM3ReadOnlyLightOnSurfaceOpacity012,
  ColorM3ReadOnlyLightOnSurfaceOpacity016,
  ColorM3ReadOnlyLightSurfaceVariantOpacity008,
  ColorM3ReadOnlyLightSurfaceVariantOpacity012,
  ColorM3ReadOnlyLightSurfaceVariantOpacity016,
  ColorM3ReadOnlyLightOnSurfaceVariantOpacity008,
  ColorM3ReadOnlyLightOnSurfaceVariantOpacity012,
  ColorM3ReadOnlyLightOnSurfaceVariantOpacity016,
  ColorM3ReadOnlyLightOutlineOpacity008,
  ColorM3ReadOnlyLightOutlineOpacity012,
  ColorM3ReadOnlyLightOutlineOpacity016,
  ColorM3ReadOnlyLightInverseOnSurfaceOpacity008,
  ColorM3ReadOnlyLightInverseOnSurfaceOpacity012,
  ColorM3ReadOnlyLightInverseOnSurfaceOpacity016,
  ColorM3ReadOnlyLightInverseSurfaceOpacity008,
  ColorM3ReadOnlyLightInverseSurfaceOpacity012,
  ColorM3ReadOnlyLightInverseSurfaceOpacity016,
  ColorM3ReadOnlyDarkSurface10,
  ColorM3ReadOnlyDarkSurface11,
  ColorM3ReadOnlyDarkSurface20,
  ColorM3ReadOnlyDarkSurface21,
  ColorM3ReadOnlyDarkSurface30,
  ColorM3ReadOnlyDarkSurface31,
  ColorM3ReadOnlyDarkSurface40,
  ColorM3ReadOnlyDarkSurface41,
  ColorM3ReadOnlyDarkSurface50,
  ColorM3ReadOnlyDarkSurface51,
  ColorM3ReadOnlyDarkWhite,
  ColorM3ReadOnlyDarkBlack,
  ColorM3ReadOnlyDarkPrimaryOpacity008,
  ColorM3ReadOnlyDarkPrimaryOpacity012,
  ColorM3ReadOnlyDarkPrimaryOpacity016,
  ColorM3ReadOnlyDarkOnPrimaryOpacity008,
  ColorM3ReadOnlyDarkOnPrimaryOpacity012,
  ColorM3ReadOnlyDarkOnPrimaryOpacity016,
  ColorM3ReadOnlyDarkOnPrimaryContainerOpacity008,
  ColorM3ReadOnlyDarkOnPrimaryContainerOpacity012,
  ColorM3ReadOnlyDarkOnPrimaryContainerOpacity016,
  ColorM3ReadOnlyDarkSecondaryOpacity008,
  ColorM3ReadOnlyDarkSecondaryOpacity012,
  ColorM3ReadOnlyDarkSecondaryOpacity016,
  ColorM3ReadOnlyDarkOnSecondaryOpacity008,
  ColorM3ReadOnlyDarkOnSecondaryOpacity012,
  ColorM3ReadOnlyDarkOnSecondaryOpacity016,
  ColorM3ReadOnlyDarkOnSecondaryContainerOpacity008,
  ColorM3ReadOnlyDarkOnSecondaryContainerOpacity012,
  ColorM3ReadOnlyDarkOnSecondaryContainerOpacity016,
  ColorM3ReadOnlyDarkTertiaryOpacity008,
  ColorM3ReadOnlyDarkTertiaryOpacity012,
  ColorM3ReadOnlyDarkTertiaryOpacity016,
  ColorM3ReadOnlyDarkOnTertiaryOpacity008,
  ColorM3ReadOnlyDarkOnTertiaryOpacity012,
  ColorM3ReadOnlyDarkOnTertiaryOpacity016,
  ColorM3ReadOnlyDarkOnTertiaryContainerOpacity008,
  ColorM3ReadOnlyDarkOnTertiaryContainerOpacity012,
  ColorM3ReadOnlyDarkOnTertiaryContainerOpacity016,
  ColorM3ReadOnlyDarkPrimaryContainerOpacity008,
  ColorM3ReadOnlyDarkPrimaryContainerOpacity012,
  ColorM3ReadOnlyDarkPrimaryContainerOpacity016,
  ColorM3ReadOnlyDarkSecondaryContainerOpacity008,
  ColorM3ReadOnlyDarkSecondaryContainerOpacity012,
  ColorM3ReadOnlyDarkSecondaryContainerOpacity016,
  ColorM3ReadOnlyDarkTertiaryContainerOpacity008,
  ColorM3ReadOnlyDarkTertiaryContainerOpacity012,
  ColorM3ReadOnlyDarkTertiaryContainerOpacity016,
  ColorM3ReadOnlyDarkErrorOpacity008,
  ColorM3ReadOnlyDarkErrorOpacity012,
  ColorM3ReadOnlyDarkErrorOpacity016,
  ColorM3ReadOnlyDarkErrorContainerOpacity008,
  ColorM3ReadOnlyDarkErrorContainerOpacity012,
  ColorM3ReadOnlyDarkErrorContainerOpacity016,
  ColorM3ReadOnlyDarkOnErrorOpacity008,
  ColorM3ReadOnlyDarkOnErrorOpacity012,
  ColorM3ReadOnlyDarkOnErrorOpacity016,
  ColorM3ReadOnlyDarkOnErrorContainerOpacity008,
  ColorM3ReadOnlyDarkOnErrorContainerOpacity012,
  ColorM3ReadOnlyDarkOnErrorContainerOpacity016,
  ColorM3ReadOnlyDarkBackgroundOpacity008,
  ColorM3ReadOnlyDarkBackgroundOpacity012,
  ColorM3ReadOnlyDarkBackgroundOpacity016,
  ColorM3ReadOnlyDarkOnBackgroundOpacity008,
  ColorM3ReadOnlyDarkOnBackgroundOpacity012,
  ColorM3ReadOnlyDarkOnBackgroundOpacity016,
  ColorM3ReadOnlyDarkSurfaceOpacity008,
  ColorM3ReadOnlyDarkSurfaceOpacity012,
  ColorM3ReadOnlyDarkSurfaceOpacity016,
  ColorM3ReadOnlyDarkOnSurfaceOpacity008,
  ColorM3ReadOnlyDarkOnSurfaceOpacity012,
  ColorM3ReadOnlyDarkOnSurfaceOpacity016,
  ColorM3ReadOnlyDarkSurfaceVariantOpacity008,
  ColorM3ReadOnlyDarkSurfaceVariantOpacity012,
  ColorM3ReadOnlyDarkSurfaceVariantOpacity016,
  ColorM3ReadOnlyDarkOnSurfaceVariantOpacity008,
  ColorM3ReadOnlyDarkOnSurfaceVariantOpacity012,
  ColorM3ReadOnlyDarkOnSurfaceVariantOpacity016,
  ColorM3ReadOnlyDarkOutlineOpacity008,
  ColorM3ReadOnlyDarkOutlineOpacity012,
  ColorM3ReadOnlyDarkOutlineOpacity016,
  ColorM3ReadOnlyDarkInverseOnSurfaceOpacity008,
  ColorM3ReadOnlyDarkInverseOnSurfaceOpacity012,
  ColorM3ReadOnlyDarkInverseOnSurfaceOpacity016,
  ColorM3ReadOnlyDarkInverseSurfaceOpacity008,
  ColorM3ReadOnlyDarkInverseSurfaceOpacity012,
  ColorM3ReadOnlyDarkInverseSurfaceOpacity016,
} from './color-token';
export const md3colors = {
  ref: {
    primary100: ColorM3RefPrimaryPrimary100,
    primary99: ColorM3RefPrimaryPrimary99,
    primary95: ColorM3RefPrimaryPrimary95,
    primary90: ColorM3RefPrimaryPrimary90,
    primary80: ColorM3RefPrimaryPrimary80,
    primary70: ColorM3RefPrimaryPrimary70,
    primary60: ColorM3RefPrimaryPrimary60,
    primary50: ColorM3RefPrimaryPrimary50,
    primary40: ColorM3RefPrimaryPrimary40,
    primary30: ColorM3RefPrimaryPrimary30,
    primary20: ColorM3RefPrimaryPrimary20,
    primary10: ColorM3RefPrimaryPrimary10,
    primary0: ColorM3RefPrimaryPrimary0,
    secondary100: ColorM3RefSecondarySecondary100,
    secondary99: ColorM3RefSecondarySecondary99,
    secondary95: ColorM3RefSecondarySecondary95,
    secondary90: ColorM3RefSecondarySecondary90,
    secondary80: ColorM3RefSecondarySecondary80,
    secondary70: ColorM3RefSecondarySecondary70,
    secondary60: ColorM3RefSecondarySecondary60,
    secondary50: ColorM3RefSecondarySecondary50,
    secondary40: ColorM3RefSecondarySecondary40,
    secondary30: ColorM3RefSecondarySecondary30,
    secondary20: ColorM3RefSecondarySecondary20,
    secondary10: ColorM3RefSecondarySecondary10,
    secondary0: ColorM3RefSecondarySecondary0,
    tertiary100: ColorM3RefTertiaryTertiary100,
    tertiary99: ColorM3RefTertiaryTertiary99,
    tertiary95: ColorM3RefTertiaryTertiary95,
    tertiary90: ColorM3RefTertiaryTertiary90,
    tertiary80: ColorM3RefTertiaryTertiary80,
    tertiary70: ColorM3RefTertiaryTertiary70,
    tertiary60: ColorM3RefTertiaryTertiary60,
    tertiary50: ColorM3RefTertiaryTertiary50,
    tertiary40: ColorM3RefTertiaryTertiary40,
    tertiary30: ColorM3RefTertiaryTertiary30,
    tertiary20: ColorM3RefTertiaryTertiary20,
    tertiary10: ColorM3RefTertiaryTertiary10,
    tertiary0: ColorM3RefTertiaryTertiary0,
    neutral100: ColorM3RefNeutralNeutral100,
    neutral99: ColorM3RefNeutralNeutral99,
    neutral95: ColorM3RefNeutralNeutral95,
    neutral90: ColorM3RefNeutralNeutral90,
    neutral80: ColorM3RefNeutralNeutral80,
    neutral70: ColorM3RefNeutralNeutral70,
    neutral60: ColorM3RefNeutralNeutral60,
    neutral50: ColorM3RefNeutralNeutral50,
    neutral40: ColorM3RefNeutralNeutral40,
    neutral30: ColorM3RefNeutralNeutral30,
    neutral20: ColorM3RefNeutralNeutral20,
    neutral10: ColorM3RefNeutralNeutral10,
    neutral0: ColorM3RefNeutralNeutral0,
    neutralVariant100: ColorM3RefNeutralVariantNeutralVariant100,
    neutralVariant99: ColorM3RefNeutralVariantNeutralVariant99,
    neutralVariant95: ColorM3RefNeutralVariantNeutralVariant95,
    neutralVariant90: ColorM3RefNeutralVariantNeutralVariant90,
    neutralVariant80: ColorM3RefNeutralVariantNeutralVariant80,
    neutralVariant70: ColorM3RefNeutralVariantNeutralVariant70,
    neutralVariant60: ColorM3RefNeutralVariantNeutralVariant60,
    neutralVariant50: ColorM3RefNeutralVariantNeutralVariant50,
    neutralVariant40: ColorM3RefNeutralVariantNeutralVariant40,
    neutralVariant30: ColorM3RefNeutralVariantNeutralVariant30,
    neutralVariant20: ColorM3RefNeutralVariantNeutralVariant20,
    neutralVariant10: ColorM3RefNeutralVariantNeutralVariant10,
    neutralVariant0: ColorM3RefNeutralVariantNeutralVariant0,
    error100: ColorM3RefErrorError100,
    error99: ColorM3RefErrorError99,
    error95: ColorM3RefErrorError95,
    error90: ColorM3RefErrorError90,
    error80: ColorM3RefErrorError80,
    error70: ColorM3RefErrorError70,
    error60: ColorM3RefErrorError60,
    error50: ColorM3RefErrorError50,
    error40: ColorM3RefErrorError40,
    error30: ColorM3RefErrorError30,
    error20: ColorM3RefErrorError20,
    error10: ColorM3RefErrorError10,
    error0: ColorM3RefErrorError0,
  },
  source: {
    seed: ColorM3SourceSeed,
    primary: ColorM3SourcePrimary,
    secondary: ColorM3SourceSecondary,
    tertiary: ColorM3SourceTertiary,
    neutral: ColorM3SourceNeutral,
    neutralVariant: ColorM3SourceNeutralVariant,
    error: ColorM3SourceError,
  },
  readOnly: {
    light: {
      surface10: ColorM3ReadOnlyLightSurface10,
      surface11: ColorM3ReadOnlyLightSurface11,
      surface20: ColorM3ReadOnlyLightSurface20,
      surface21: ColorM3ReadOnlyLightSurface21,
      surface30: ColorM3ReadOnlyLightSurface30,
      surface31: ColorM3ReadOnlyLightSurface31,
      surface40: ColorM3ReadOnlyLightSurface40,
      surface41: ColorM3ReadOnlyLightSurface41,
      surface50: ColorM3ReadOnlyLightSurface50,
      surface51: ColorM3ReadOnlyLightSurface51,
      black: ColorM3ReadOnlyLightBlack,
      white: ColorM3ReadOnlyLightWhite,
      primaryOpacity008: ColorM3ReadOnlyLightPrimaryOpacity008,
      primaryOpacity012: ColorM3ReadOnlyLightPrimaryOpacity012,
      primaryOpacity016: ColorM3ReadOnlyLightPrimaryOpacity016,
      onPrimaryOpacity008: ColorM3ReadOnlyLightOnPrimaryOpacity008,
      onPrimaryOpacity012: ColorM3ReadOnlyLightOnPrimaryOpacity012,
      onPrimaryOpacity016: ColorM3ReadOnlyLightOnPrimaryOpacity016,
      onPrimaryOpacityContainer008: ColorM3ReadOnlyLightOnPrimaryContainerOpacity008,
      onPrimaryOpacityContainer012: ColorM3ReadOnlyLightOnPrimaryContainerOpacity012,
      onPrimaryOpacityContainer016: ColorM3ReadOnlyLightOnPrimaryContainerOpacity016,
      secondaryOpacity008: ColorM3ReadOnlyLightSecondaryOpacity008,
      secondaryOpacity012: ColorM3ReadOnlyLightSecondaryOpacity012,
      secondaryOpacity016: ColorM3ReadOnlyLightSecondaryOpacity016,
      onSecondaryOpacity008: ColorM3ReadOnlyLightOnSecondaryOpacity008,
      onSecondaryOpacity012: ColorM3ReadOnlyLightOnSecondaryOpacity012,
      onSecondaryOpacity016: ColorM3ReadOnlyLightOnSecondaryOpacity016,
      onSecondaryContainer008: ColorM3ReadOnlyLightOnSecondaryContainerOpacity008,
      onSecondaryContainer012: ColorM3ReadOnlyLightOnSecondaryContainerOpacity012,
      onSecondaryContainer016: ColorM3ReadOnlyLightOnSecondaryContainerOpacity016,
      tertiaryOpacity008: ColorM3ReadOnlyLightTertiaryOpacity008,
      tertiaryOpacity012: ColorM3ReadOnlyLightTertiaryOpacity012,
      tertiaryOpacity016: ColorM3ReadOnlyLightTertiaryOpacity016,
      onTertiaryOpacity008: ColorM3ReadOnlyLightOnTertiaryOpacity008,
      onTertiaryOpacity012: ColorM3ReadOnlyLightOnTertiaryOpacity012,
      onTertiaryOpacity016: ColorM3ReadOnlyLightOnTertiaryOpacity016,
      onTertiaryContainerOpacity008: ColorM3ReadOnlyLightOnTertiaryContainerOpacity008,
      onTertiaryContainerOpacity012: ColorM3ReadOnlyLightOnTertiaryContainerOpacity012,
      onTertiaryContainerOpacity016: ColorM3ReadOnlyLightOnTertiaryContainerOpacity016,
      primaryContainerOpacity008: ColorM3ReadOnlyLightPrimaryContainerOpacity008,
      primaryContainerOpacity012: ColorM3ReadOnlyLightPrimaryContainerOpacity012,
      primaryContainerOpacity016: ColorM3ReadOnlyLightPrimaryContainerOpacity016,
      secondaryContainerOpacity008: ColorM3ReadOnlyLightSecondaryContainerOpacity008,
      secondaryContainerOpacity012: ColorM3ReadOnlyLightSecondaryContainerOpacity012,
      secondaryContainerOpacity016: ColorM3ReadOnlyLightSecondaryContainerOpacity016,
      tertiaryContainerOpacity008: ColorM3ReadOnlyLightTertiaryContainerOpacity008,
      tertiaryContainerOpacity012: ColorM3ReadOnlyLightTertiaryContainerOpacity012,
      tertiaryContainerOpacity016: ColorM3ReadOnlyLightTertiaryContainerOpacity016,
      errorOpacity008: ColorM3ReadOnlyLightErrorOpacity008,
      errorOpacity012: ColorM3ReadOnlyLightErrorOpacity012,
      errorOpacity016: ColorM3ReadOnlyLightErrorOpacity016,
      errorContainerOpacity008: ColorM3ReadOnlyLightErrorContainerOpacity008,
      errorContainerOpacity012: ColorM3ReadOnlyLightErrorContainerOpacity012,
      errorContainerOpacity016: ColorM3ReadOnlyLightErrorContainerOpacity016,
      onErrorOpacity008: ColorM3ReadOnlyLightOnErrorOpacity008,
      onErrorOpacity012: ColorM3ReadOnlyLightOnErrorOpacity012,
      onErrorOpacity016: ColorM3ReadOnlyLightOnErrorOpacity016,
      onErrorContainerOpacity008: ColorM3ReadOnlyLightOnErrorContainerOpacity008,
      onErrorContainerOpacity012: ColorM3ReadOnlyLightOnErrorContainerOpacity012,
      onErrorContainerOpacity016: ColorM3ReadOnlyLightOnErrorContainerOpacity016,
      backgroundOpacity008: ColorM3ReadOnlyLightBackgroundOpacity008,
      backgroundOpacity012: ColorM3ReadOnlyLightBackgroundOpacity012,
      backgroundOpacity016: ColorM3ReadOnlyLightBackgroundOpacity016,
      onBackgroundOpacity008: ColorM3ReadOnlyLightOnBackgroundOpacity008,
      onBackgroundOpacity012: ColorM3ReadOnlyLightOnBackgroundOpacity012,
      onBackgroundOpacity016: ColorM3ReadOnlyLightOnBackgroundOpacity016,
      surfaceOpacity008: ColorM3ReadOnlyLightSurfaceOpacity008,
      surfaceOpacity012: ColorM3ReadOnlyLightSurfaceOpacity012,
      surfaceOpacity016: ColorM3ReadOnlyLightSurfaceOpacity016,
      onSurfaceOpacity008: ColorM3ReadOnlyLightOnSurfaceOpacity008,
      onSurfaceOpacity012: ColorM3ReadOnlyLightOnSurfaceOpacity012,
      onSurfaceOpacity016: ColorM3ReadOnlyLightOnSurfaceOpacity016,
      surfaceVariantOpacity008: ColorM3ReadOnlyLightSurfaceVariantOpacity008,
      surfaceVariantOpacity012: ColorM3ReadOnlyLightSurfaceVariantOpacity012,
      surfaceVariantOpacity016: ColorM3ReadOnlyLightSurfaceVariantOpacity016,
      onSurfaceVariantOpacity008: ColorM3ReadOnlyLightOnSurfaceVariantOpacity008,
      onSurfaceVariantOpacity012: ColorM3ReadOnlyLightOnSurfaceVariantOpacity012,
      onSurfaceVariantOpacity016: ColorM3ReadOnlyLightOnSurfaceVariantOpacity016,
      outlineOpacity008: ColorM3ReadOnlyLightOutlineOpacity008,
      outlineOpacity012: ColorM3ReadOnlyLightOutlineOpacity012,
      outlineOpacity016: ColorM3ReadOnlyLightOutlineOpacity016,
      inverseOnSurfaceOpacity008: ColorM3ReadOnlyLightInverseOnSurfaceOpacity008,
      inverseOnSurfaceOpacity012: ColorM3ReadOnlyLightInverseOnSurfaceOpacity012,
      inverseOnSurfaceOpacity016: ColorM3ReadOnlyLightInverseOnSurfaceOpacity016,
      inverseSurfaceOpacity008: ColorM3ReadOnlyLightInverseSurfaceOpacity008,
      inverseSurfaceOpacity012: ColorM3ReadOnlyLightInverseSurfaceOpacity012,
      inverseSurfaceOpacity016: ColorM3ReadOnlyLightInverseSurfaceOpacity016,
    },
    dark: {
      surface10: ColorM3ReadOnlyDarkSurface10,
      surface11: ColorM3ReadOnlyDarkSurface11,
      surface20: ColorM3ReadOnlyDarkSurface20,
      surface21: ColorM3ReadOnlyDarkSurface21,
      surface30: ColorM3ReadOnlyDarkSurface30,
      surface31: ColorM3ReadOnlyDarkSurface31,
      surface40: ColorM3ReadOnlyDarkSurface40,
      surface41: ColorM3ReadOnlyDarkSurface41,
      surface50: ColorM3ReadOnlyDarkSurface50,
      surface51: ColorM3ReadOnlyDarkSurface51,
      black: ColorM3ReadOnlyDarkWhite,
      white: ColorM3ReadOnlyDarkBlack,
      primaryOpacity008: ColorM3ReadOnlyDarkPrimaryOpacity008,
      primaryOpacity012: ColorM3ReadOnlyDarkPrimaryOpacity012,
      primaryOpacity016: ColorM3ReadOnlyDarkPrimaryOpacity016,
      onPrimaryOpacity008: ColorM3ReadOnlyDarkOnPrimaryOpacity008,
      onPrimaryOpacity012: ColorM3ReadOnlyDarkOnPrimaryOpacity012,
      onPrimaryOpacity016: ColorM3ReadOnlyDarkOnPrimaryOpacity016,
      onPrimaryOpacityContainer008: ColorM3ReadOnlyDarkOnPrimaryContainerOpacity008,
      onPrimaryOpacityContainer012: ColorM3ReadOnlyDarkOnPrimaryContainerOpacity012,
      onPrimaryOpacityContainer016: ColorM3ReadOnlyDarkOnPrimaryContainerOpacity016,
      secondaryOpacity008: ColorM3ReadOnlyDarkSecondaryOpacity008,
      secondaryOpacity012: ColorM3ReadOnlyDarkSecondaryOpacity012,
      secondaryOpacity016: ColorM3ReadOnlyDarkSecondaryOpacity016,
      onSecondaryOpacity008: ColorM3ReadOnlyDarkOnSecondaryOpacity008,
      onSecondaryOpacity012: ColorM3ReadOnlyDarkOnSecondaryOpacity012,
      onSecondaryOpacity016: ColorM3ReadOnlyDarkOnSecondaryOpacity016,
      onSecondaryContainer008: ColorM3ReadOnlyDarkOnSecondaryContainerOpacity008,
      onSecondaryContainer012: ColorM3ReadOnlyDarkOnSecondaryContainerOpacity012,
      onSecondaryContainer016: ColorM3ReadOnlyDarkOnSecondaryContainerOpacity016,
      tertiaryOpacity008: ColorM3ReadOnlyDarkTertiaryOpacity008,
      tertiaryOpacity012: ColorM3ReadOnlyDarkTertiaryOpacity012,
      tertiaryOpacity016: ColorM3ReadOnlyDarkTertiaryOpacity016,
      onTertiaryOpacity008: ColorM3ReadOnlyDarkOnTertiaryOpacity008,
      onTertiaryOpacity012: ColorM3ReadOnlyDarkOnTertiaryOpacity012,
      onTertiaryOpacity016: ColorM3ReadOnlyDarkOnTertiaryOpacity016,
      onTertiaryContainerOpacity008: ColorM3ReadOnlyDarkOnTertiaryContainerOpacity008,
      onTertiaryContainerOpacity012: ColorM3ReadOnlyDarkOnTertiaryContainerOpacity012,
      onTertiaryContainerOpacity016: ColorM3ReadOnlyDarkOnTertiaryContainerOpacity016,
      primaryContainerOpacity008: ColorM3ReadOnlyDarkPrimaryContainerOpacity008,
      primaryContainerOpacity012: ColorM3ReadOnlyDarkPrimaryContainerOpacity012,
      primaryContainerOpacity016: ColorM3ReadOnlyDarkPrimaryContainerOpacity016,
      secondaryContainerOpacity008: ColorM3ReadOnlyDarkSecondaryContainerOpacity008,
      secondaryContainerOpacity012: ColorM3ReadOnlyDarkSecondaryContainerOpacity012,
      secondaryContainerOpacity016: ColorM3ReadOnlyDarkSecondaryContainerOpacity016,
      tertiaryContainerOpacity008: ColorM3ReadOnlyDarkTertiaryContainerOpacity008,
      tertiaryContainerOpacity012: ColorM3ReadOnlyDarkTertiaryContainerOpacity012,
      tertiaryContainerOpacity016: ColorM3ReadOnlyDarkTertiaryContainerOpacity016,
      errorOpacity008: ColorM3ReadOnlyDarkErrorOpacity008,
      errorOpacity012: ColorM3ReadOnlyDarkErrorOpacity012,
      errorOpacity016: ColorM3ReadOnlyDarkErrorOpacity016,
      errorContainerOpacity008: ColorM3ReadOnlyDarkErrorContainerOpacity008,
      errorContainerOpacity012: ColorM3ReadOnlyDarkErrorContainerOpacity012,
      errorContainerOpacity016: ColorM3ReadOnlyDarkErrorContainerOpacity016,
      onErrorOpacity008: ColorM3ReadOnlyDarkOnErrorOpacity008,
      onErrorOpacity012: ColorM3ReadOnlyDarkOnErrorOpacity012,
      onErrorOpacity016: ColorM3ReadOnlyDarkOnErrorOpacity016,
      onErrorContainerOpacity008: ColorM3ReadOnlyDarkOnErrorContainerOpacity008,
      onErrorContainerOpacity012: ColorM3ReadOnlyDarkOnErrorContainerOpacity012,
      onErrorContainerOpacity016: ColorM3ReadOnlyDarkOnErrorContainerOpacity016,
      backgroundOpacity008: ColorM3ReadOnlyDarkBackgroundOpacity008,
      backgroundOpacity012: ColorM3ReadOnlyDarkBackgroundOpacity012,
      backgroundOpacity016: ColorM3ReadOnlyDarkBackgroundOpacity016,
      onBackgroundOpacity008: ColorM3ReadOnlyDarkOnBackgroundOpacity008,
      onBackgroundOpacity012: ColorM3ReadOnlyDarkOnBackgroundOpacity012,
      onBackgroundOpacity016: ColorM3ReadOnlyDarkOnBackgroundOpacity016,
      surfaceOpacity008: ColorM3ReadOnlyDarkSurfaceOpacity008,
      surfaceOpacity012: ColorM3ReadOnlyDarkSurfaceOpacity012,
      surfaceOpacity016: ColorM3ReadOnlyDarkSurfaceOpacity016,
      onSurfaceOpacity008: ColorM3ReadOnlyDarkOnSurfaceOpacity008,
      onSurfaceOpacity012: ColorM3ReadOnlyDarkOnSurfaceOpacity012,
      onSurfaceOpacity016: ColorM3ReadOnlyDarkOnSurfaceOpacity016,
      surfaceVariantOpacity008: ColorM3ReadOnlyDarkSurfaceVariantOpacity008,
      surfaceVariantOpacity012: ColorM3ReadOnlyDarkSurfaceVariantOpacity012,
      surfaceVariantOpacity016: ColorM3ReadOnlyDarkSurfaceVariantOpacity016,
      onSurfaceVariantOpacity008: ColorM3ReadOnlyDarkOnSurfaceVariantOpacity008,
      onSurfaceVariantOpacity012: ColorM3ReadOnlyDarkOnSurfaceVariantOpacity012,
      onSurfaceVariantOpacity016: ColorM3ReadOnlyDarkOnSurfaceVariantOpacity016,
      outlineOpacity008: ColorM3ReadOnlyDarkOutlineOpacity008,
      outlineOpacity012: ColorM3ReadOnlyDarkOutlineOpacity012,
      outlineOpacity016: ColorM3ReadOnlyDarkOutlineOpacity016,
      inverseOnSurfaceOpacity008: ColorM3ReadOnlyDarkInverseOnSurfaceOpacity008,
      inverseOnSurfaceOpacity012: ColorM3ReadOnlyDarkInverseOnSurfaceOpacity012,
      inverseOnSurfaceOpacity016: ColorM3ReadOnlyDarkInverseOnSurfaceOpacity016,
      inverseSurfaceOpacity008: ColorM3ReadOnlyDarkInverseSurfaceOpacity008,
      inverseSurfaceOpacity012: ColorM3ReadOnlyDarkInverseSurfaceOpacity012,
      inverseSurfaceOpacity016: ColorM3ReadOnlyDarkInverseSurfaceOpacity016,
    },
  },
};
export const refColor = {
  amber50: Colors.amber50,
  amber100: Colors.amber100,
  amber200: Colors.amber200,
  amber300: Colors.amber300,
  amber400: Colors.amber400,
  amber500: Colors.amber500,
  amber600: Colors.amber600,
  amber700: Colors.amber700,
  amber800: Colors.amber800,
  amber900: Colors.amber900,
  black: Colors.black,
  blue50: Colors.blue50,
  blue100: Colors.blue100,
  blue200: Colors.blue200,
  blue300: Colors.blue300,
  blue400: Colors.blue400,
  blue500: Colors.blue500,
  blue600: Colors.blue600,
  blue700: Colors.blue700,
  blue800: Colors.blue800,
  blue900: Colors.blue900,
  blueGrey50: Colors.blueGrey50,
  blueGrey100: Colors.blueGrey100,
  blueGrey200: Colors.blueGrey200,
  blueGrey300: Colors.blueGrey300,
  blueGrey400: Colors.blueGrey400,
  blueGrey500: Colors.blueGrey500,
  blueGrey600: Colors.blueGrey600,
  blueGrey700: Colors.blueGrey700,
  blueGrey800: Colors.blueGrey800,
  blueGrey900: Colors.blueGrey900,
  brown50: Colors.brown50,
  brown100: Colors.brown100,
  brown200: Colors.brown200,
  brown300: Colors.brown300,
  brown400: Colors.brown400,
  brown500: Colors.brown500,
  brown600: Colors.brown600,
  brown700: Colors.brown700,
  brown800: Colors.brown800,
  brown900: Colors.brown900,
  green50: Colors.green50,
  green100: Colors.green100,
  green200: Colors.green200,
  green300: Colors.green300,
  green400: Colors.green400,
  green500: Colors.green500,
  green600: Colors.green600,
  green700: Colors.green700,
  green800: Colors.green800,
  green900: Colors.green900,
  grey50: Colors.grey50,
  grey100: Colors.grey100,
  grey200: Colors.grey200,
  grey300: Colors.grey300,
  grey400: Colors.grey400,
  grey500: Colors.grey500,
  grey600: Colors.grey600,
  grey700: Colors.grey700,
  grey800: Colors.grey800,
  grey900: Colors.grey900,
  orange50: Colors.orange50,
  orange100: Colors.orange100,
  orange200: Colors.orange200,
  orange300: Colors.orange300,
  orange400: Colors.orange400,
  orange500: Colors.orange500,
  orange600: Colors.orange600,
  orange700: Colors.orange700,
  orange800: Colors.orange800,
  orange900: Colors.orange900,
  purple50: Colors.purple50,
  purple100: Colors.purple100,
  purple200: Colors.purple200,
  purple300: Colors.purple300,
  purple400: Colors.purple400,
  purple500: Colors.purple500,
  purple600: Colors.purple600,
  purple700: Colors.purple700,
  purple800: Colors.purple800,
  purple900: Colors.purple900,
  red50: Colors.red50,
  red100: Colors.red100,
  red200: Colors.red200,
  red300: Colors.red300,
  red400: Colors.red400,
  red500: Colors.red500,
  red600: Colors.red600,
  red700: Colors.red700,
  red800: Colors.red800,
  red900: Colors.red900,
  white: Colors.white,
  yellow50: Colors.yellow50,
  yellow100: Colors.yellow100,
  yellow200: Colors.yellow200,
  yellow300: Colors.yellow300,
  yellow400: Colors.yellow400,
  yellow500: Colors.yellow500,
  yellow600: Colors.yellow600,
  yellow700: Colors.yellow700,
  yellow800: Colors.yellow800,
  yellow900: Colors.yellow900,
};

export const lightColors = {
  ...DefaultTheme.colors,
  primary: ColorM3SysLightPrimary,
  onPrimary: ColorM3SysLightOnPrimary,
  primaryContainer: ColorM3SysLightPrimaryContainer,
  onPrimaryContainer: ColorM3SysLightOnPrimaryContainer,
  secondary: ColorM3SysLightSecondary,
  onSecondary: ColorM3SysLightOnSecondary,
  secondaryContainer: ColorM3SysLightSecondaryContainer,
  onSecondaryContainer: ColorM3SysLightOnSecondaryContainer,
  tertiary: ColorM3SysLightTertiary,
  onTertiary: ColorM3SysLightOnTertiary,
  tertiaryContainer: ColorM3SysLightTertiaryContainer,
  onTertiaryContainer: ColorM3SysLightOnTertiaryContainer,
  error: ColorM3SysLightError,
  onError: ColorM3SysLightOnError,
  errorContainer: ColorM3SysLightErrorContainer,
  onErrorContainer: ColorM3SysLightOnErrorContainer,
  background: ColorM3SysLightBackground,
  onBackground: ColorM3SysLightOnBackground,
  surface: ColorM3SysLightSurface,
  onSurface: ColorM3SysLightOnSurface,
  surfaceVariant: ColorM3SysLightSurfaceVariant,
  onSurfaceVariant: ColorM3SysLightOnSurfaceVariant,
  outline: ColorM3SysLightOutline,
  inverseOnSurface: ColorM3SysLightInverseOnSurface,
  inverseSurface: ColorM3SysLightInverseSurface,
};
export const darkColors = {
  ...DarkTheme.colors,
  primary: ColorM3SysDarkPrimary,
  onPrimary: ColorM3SysDarkOnPrimary,
  primaryContainer: ColorM3SysDarkPrimaryContainer,
  onPrimaryContainer: ColorM3SysDarkOnPrimaryContainer,
  secondary: ColorM3SysDarkSecondary,
  onSecondary: ColorM3SysDarkOnSecondary,
  secondaryContainer: ColorM3SysDarkSecondaryContainer,
  onSecondaryContainer: ColorM3SysDarkOnSecondaryContainer,
  tertiary: ColorM3SysDarkTertiary,
  onTertiary: ColorM3SysDarkOnTertiary,
  tertiaryContainer: ColorM3SysDarkTertiaryContainer,
  onTertiaryContainer: ColorM3SysDarkOnTertiaryContainer,
  error: ColorM3SysDarkError,
  onError: ColorM3SysDarkOnError,
  errorContainer: ColorM3SysDarkErrorContainer,
  onErrorContainer: ColorM3SysDarkOnErrorContainer,
  background: ColorM3SysDarkBackground,
  onBackground: ColorM3SysDarkOnBackground,
  surface: ColorM3SysDarkSurface,
  onSurface: ColorM3SysDarkOnSurface,
  surfaceVariant: ColorM3SysDarkSurfaceVariant,
  onSurfaceVariant: ColorM3SysDarkOnSurfaceVariant,
  outline: ColorM3SysDarkOutline,
  inverseOnSurface: ColorM3SysDarkInverseOnSurface,
  inverseSurface: ColorM3SysDarkInverseSurface,
};
export type MD3Colors = typeof md3colors;

export type RefColor = typeof refColor;
